# Generated by Django 3.2.16 on 2023-03-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_api',
            new_name='students',
        ),
    ]
